# Generated by Django 3.0.10 on 2020-10-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25, unique=True)),
                ('abbr', models.CharField(max_length=2, unique=True)),
                ('tax_rate', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
