# Generated by Django 3.0.10 on 2020-10-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_multiple_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='primary',
            field=models.BooleanField(default=True),
        ),
    ]
