# Generated by Django 3.0.10 on 2020-10-17 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_updated_image_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='url',
        ),
    ]
